# Generated by Django 4.2.8 on 2024-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("st_id", models.IntegerField(primary_key=True, serialize=False)),
                ("st_name", models.CharField(max_length=50)),
                ("st_email", models.EmailField(max_length=254)),
                ("st_address", models.CharField(max_length=100)),
                ("st_class", models.CharField(max_length=10)),
            ],
        ),
    ]
