# Generated by Django 4.2.8 on 2024-09-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_rest", "0002_category_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_price",
            field=models.FloatField(max_length=100),
        ),
    ]
